FROM node:22-alpine

WORKDIR /app

COPY worker/package*.json ./

RUN npm config set registry https://registry.npmjs.org/
RUN npm install

COPY worker/. ./
COPY shared ./shared

CMD ["npm", "run", "worker"]