FROM node:22-alpine

WORKDIR /app

COPY api/package*.json ./

RUN npm config set registry https://registry.npmjs.org/
RUN npm install

COPY api/. ./
COPY shared/ ./shared/

EXPOSE 3000

CMD ["npm", "run", "dev"]
# production
# CMD ["npm", "start"]